version: '3.1'
services:
  nuntio:
    image: ${DOCKER_IMAGE}
    ports:
      - ${DOCKER_IP}::8080
    environment:
      NUNTIO_CONSUL_HOST: consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      nuntio.xenit.eu/service: nuntio
      nuntio.xenit.eu/check/readiness/type: http
      nuntio.xenit.eu/check/readiness/interval: 30s
      nuntio.xenit.eu/check/readiness/path: /actuator/health/readiness

  consul:
    image: docker.io/library/consul:latest
    command:
      - agent
      - -dev
      - -client=0.0.0.0
    healthcheck:
      test:
        - CMD
        - consul
        - info