on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew check
      - name: Upload test reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-build
          path: '**/build/reports/'
      - name: Upload analysis to sonarcloud
        if: "${{ env.SONAR_TOKEN != '' }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_nuntio -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io
  publish:
    needs:
      - build
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Log in to docker hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to Xenit docker images
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.XENIT_DOCKER_REGISTRY_URL }}
          username: ${{ secrets.XENIT_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.XENIT_DOCKER_REGISTRY_PASSWORD }}
      - name: Publish docker images
        run: ./gradlew pushDockerImage
