on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew check
      - name: Upload test reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-build
          path: '**/build/reports/'
      - name: Upload analysis to sonarcloud
        if: "${{ env.SONAR_TOKEN != '' }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_nuntio -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io